package com.jiqu.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTICE_TABLE".
 */
@Entity
public class NoticeTable {

    @Id
    private Long id;
    private String notice;
    private String time;

    @Generated
    public NoticeTable() {
    }

    public NoticeTable(Long id) {
        this.id = id;
    }

    @Generated
    public NoticeTable(Long id, String notice, String time) {
        this.id = id;
        this.notice = notice;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNotice() {
        return notice;
    }

    public void setNotice(String notice) {
        this.notice = notice;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
